name: Hugging Face Upload

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install huggingface_hub
      - name: Depuración
        run: |
          echo "Token de acceso: ${{ secrets.HUGGING_FACE_TOKEN }}"
          echo "Repositorio: $GITHUB_REPOSITORY"
      - name: Upload to Hugging Face
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: |
          python -m huggingface_hub upload --repo $GITHUB_REPOSITORY --token $HUGGING_FACE_TOKEN
